-- Seed rental FAQ entries into the faqs table
INSERT INTO faqs (section, question, answer, sort_order, is_published, show_on_blog, show_on_category)
VALUES
  ('rental', 'Do you offer fancy dress on rent?', 'Yes, every costume in our shop is available on rent. Rent starts from ₹200 per event. You can visit our Krishna Nagar, Delhi shop or message us on WhatsApp to check what is available.', 1, true, true, true),
  ('rental', 'What is the security deposit for renting a costume?', 'We take a refundable security deposit along with the rent. It depends on the costume: ₹500 deposit for costumes up to ₹200 rent, ₹1,000 for ₹201–₹500 rent, and ₹2,000 for costumes above ₹500 rent. You get the full deposit back when you return the costume.', 2, true, true, true),
  ('rental', 'How does the costume rental process work?', 'It is simple. Send us a WhatsApp message with the costume you need and your event date. Come to our Krishna Nagar shop to try the costume, or we can send it to you via Porter or Rapido. Pay the rent plus deposit. After your event, return the costume and collect your deposit.', 3, true, true, true),
  ('rental', 'Can I rent fancy dress online or do I need to visit the shop?', 'You can enquire and reserve on WhatsApp (+91 93113 65366). For pickup, visit our shop in Krishna Nagar, East Delhi. If you cannot come, we can arrange delivery through Porter or Rapido to your doorstep.', 4, true, true, true),
  ('rental', 'Can I try the costume before renting?', 'Yes. If you visit our Krishna Nagar shop, you can try different sizes and styles before you decide. We recommend visiting the shop especially for dance costumes where the fit matters.', 5, true, true, true),
  ('rental', 'How early should I book a rental costume?', 'During busy months like August to November (school annual days) and January to February (Republic Day), costumes go fast. We suggest booking at least one week ahead. For popular costumes like Kathak or Krishna dress, two weeks is better. Off-season, even 2–3 days notice works.', 6, true, true, true),
  ('rental', 'What if the costume gets damaged or stained?', 'Normal wear is fine — kids are kids, we understand. Small marks that come out in wash are not a problem. If there is major damage like a tear or permanent stain, a part of the deposit may be adjusted to cover the repair. We are fair about it and will show you the issue.', 7, true, false, false),
  ('rental', 'For how many days can I keep the rented costume?', 'The standard rental is for one event, which usually means 1–2 days. If your child has a rehearsal and then the event on separate days, just let us know and we will work it out. Extra days can be arranged for a small additional charge.', 8, true, false, false),
  ('rental', 'Do you rent costumes for adults or only for kids?', 'Most of our rental costumes are for kids aged 3 to 13 years, which covers school functions and competitions. We do have some adult-size costumes for teachers and parents. WhatsApp us your requirement and we will check availability.', 9, true, false, false),
  ('rental', 'Can I rent multiple costumes for a school group or class?', 'Absolutely. If you need 10 or more costumes for a class performance or school event, we offer special group rates. Teachers and school coordinators can WhatsApp us with the list and we will put together a package with a group discount.', 10, true, true, true),
  ('rental', 'Is home delivery available for rented costumes?', 'Yes. We can arrange delivery through Porter or Rapido to anywhere in Delhi-NCR. You pay the delivery charge directly to the delivery partner. Many parents find this convenient when they cannot visit the shop.', 11, true, false, true),
  ('rental', 'How do I return the rented costume?', 'Bring it back to our Krishna Nagar shop after your event. No need to wash it — just return it as is. We will check the costume and return your full deposit on the spot. If you used delivery, you can send it back via Porter or Rapido.', 12, true, false, true)
ON CONFLICT DO NOTHING;
